// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ObserverNetLite.Data;

#nullable disable

namespace ObserverNetLite.Infrastructure.Migrations
{
    [DbContext(typeof(ObserverNetLiteDbContext))]
    [Migration("20251123105021_AddGuestRolePermissions")]
    partial class AddGuestRolePermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ObserverNetLite.Core.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Route")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Menus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000001-0000-0000-0000-000000000001"),
                            Icon = "dashboard",
                            IsActive = true,
                            Name = "dashboard",
                            Order = 1,
                            Route = "/dashboard",
                            Title = "Dashboard"
                        },
                        new
                        {
                            Id = new Guid("40000002-0000-0000-0000-000000000002"),
                            Icon = "people",
                            IsActive = true,
                            Name = "users",
                            Order = 2,
                            Route = "/users",
                            Title = "Users"
                        },
                        new
                        {
                            Id = new Guid("40000003-0000-0000-0000-000000000003"),
                            Icon = "shield",
                            IsActive = true,
                            Name = "roles",
                            Order = 3,
                            Route = "/roles",
                            Title = "Roles"
                        },
                        new
                        {
                            Id = new Guid("40000005-0000-0000-0000-000000000005"),
                            Icon = "menu",
                            IsActive = true,
                            Name = "menus",
                            Order = 4,
                            Route = "/menus",
                            Title = "Menus"
                        },
                        new
                        {
                            Id = new Guid("40000004-0000-0000-0000-000000000004"),
                            Icon = "settings",
                            IsActive = true,
                            Name = "settings",
                            Order = 5,
                            Route = "/settings",
                            Title = "Settings"
                        });
                });

            modelBuilder.Entity("ObserverNetLite.Core.Entities.MenuPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("MenuId", "PermissionId")
                        .IsUnique();

                    b.ToTable("MenuPermissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("60000001-0000-0000-0000-000000000001"),
                            MenuId = new Guid("40000001-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("60000002-0000-0000-0000-000000000002"),
                            MenuId = new Guid("40000002-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("30000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("60000003-0000-0000-0000-000000000003"),
                            MenuId = new Guid("40000003-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("30000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("60000004-0000-0000-0000-000000000004"),
                            MenuId = new Guid("40000005-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("30000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("60000005-0000-0000-0000-000000000005"),
                            MenuId = new Guid("40000004-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("30000001-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("ObserverNetLite.Core.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000001"),
                            Category = "User",
                            Code = "USER_VIEW",
                            Description = "View user list and details",
                            Name = "View Users"
                        },
                        new
                        {
                            Id = new Guid("10000002-0000-0000-0000-000000000002"),
                            Category = "User",
                            Code = "USER_CREATE",
                            Description = "Create new users",
                            Name = "Create User"
                        },
                        new
                        {
                            Id = new Guid("10000003-0000-0000-0000-000000000003"),
                            Category = "User",
                            Code = "USER_EDIT",
                            Description = "Edit existing users",
                            Name = "Edit User"
                        },
                        new
                        {
                            Id = new Guid("10000004-0000-0000-0000-000000000004"),
                            Category = "User",
                            Code = "USER_DELETE",
                            Description = "Delete users",
                            Name = "Delete User"
                        },
                        new
                        {
                            Id = new Guid("20000001-0000-0000-0000-000000000001"),
                            Category = "Role",
                            Code = "ROLE_VIEW",
                            Description = "View role list and details",
                            Name = "View Roles"
                        },
                        new
                        {
                            Id = new Guid("20000002-0000-0000-0000-000000000002"),
                            Category = "Role",
                            Code = "ROLE_CREATE",
                            Description = "Create new roles",
                            Name = "Create Role"
                        },
                        new
                        {
                            Id = new Guid("20000003-0000-0000-0000-000000000003"),
                            Category = "Role",
                            Code = "ROLE_EDIT",
                            Description = "Edit existing roles",
                            Name = "Edit Role"
                        },
                        new
                        {
                            Id = new Guid("20000004-0000-0000-0000-000000000004"),
                            Category = "Role",
                            Code = "ROLE_DELETE",
                            Description = "Delete roles",
                            Name = "Delete Role"
                        },
                        new
                        {
                            Id = new Guid("30000001-0000-0000-0000-000000000001"),
                            Category = "Menu",
                            Code = "MENU_VIEW",
                            Description = "View menu list and details",
                            Name = "View Menus"
                        },
                        new
                        {
                            Id = new Guid("30000002-0000-0000-0000-000000000002"),
                            Category = "Menu",
                            Code = "MENU_CREATE",
                            Description = "Create new menus",
                            Name = "Create Menu"
                        },
                        new
                        {
                            Id = new Guid("30000003-0000-0000-0000-000000000003"),
                            Category = "Menu",
                            Code = "MENU_EDIT",
                            Description = "Edit existing menus",
                            Name = "Edit Menu"
                        },
                        new
                        {
                            Id = new Guid("30000004-0000-0000-0000-000000000004"),
                            Category = "Menu",
                            Code = "MENU_DELETE",
                            Description = "Delete menus",
                            Name = "Delete Menu"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Category = "Dashboard",
                            Code = "view_dashboard",
                            Description = "Access to dashboard page",
                            Name = "View Dashboard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Category = "Users",
                            Code = "view_users",
                            Description = "Access to users page",
                            Name = "View Users"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Category = "Users",
                            Code = "create_user",
                            Description = "Create new users",
                            Name = "Create User"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Category = "Users",
                            Code = "edit_user",
                            Description = "Edit existing users",
                            Name = "Edit User"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Category = "Users",
                            Code = "delete_user",
                            Description = "Delete users",
                            Name = "Delete User"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Category = "Roles",
                            Code = "view_roles",
                            Description = "Access to roles page",
                            Name = "View Roles"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Category = "Roles",
                            Code = "create_role",
                            Description = "Create new roles",
                            Name = "Create Role"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Category = "Roles",
                            Code = "edit_role",
                            Description = "Edit existing roles",
                            Name = "Edit Role"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Category = "Roles",
                            Code = "delete_role",
                            Description = "Delete roles",
                            Name = "Delete Role"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000a"),
                            Category = "Roles",
                            Code = "assign_permissions",
                            Description = "Assign permissions to roles",
                            Name = "Assign Permissions"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000b"),
                            Category = "Menus",
                            Code = "view_menus",
                            Description = "Access to menus page",
                            Name = "View Menus"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000c"),
                            Category = "Menus",
                            Code = "create_menu",
                            Description = "Create new menus",
                            Name = "Create Menu"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000d"),
                            Category = "Menus",
                            Code = "edit_menu",
                            Description = "Edit existing menus",
                            Name = "Edit Menu"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000e"),
                            Category = "Menus",
                            Code = "delete_menu",
                            Description = "Delete menus",
                            Name = "Delete Menu"
                        });
                });

            modelBuilder.Entity("ObserverNetLite.Core.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Administrator role with full access",
                            IsActive = true,
                            Name = "admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Guest role with limited access",
                            IsActive = true,
                            Name = "guest"
                        });
                });

            modelBuilder.Entity("ObserverNetLite.Core.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000001-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000001-0000-0000-0000-000000000001"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("50000002-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000002-0000-0000-0000-000000000002"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("50000003-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("10000003-0000-0000-0000-000000000003"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("50000004-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("10000004-0000-0000-0000-000000000004"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("50000005-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("20000001-0000-0000-0000-000000000001"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("50000006-0000-0000-0000-000000000006"),
                            PermissionId = new Guid("20000002-0000-0000-0000-000000000002"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("50000007-0000-0000-0000-000000000007"),
                            PermissionId = new Guid("20000003-0000-0000-0000-000000000003"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("50000008-0000-0000-0000-000000000008"),
                            PermissionId = new Guid("20000004-0000-0000-0000-000000000004"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("50000009-0000-0000-0000-000000000009"),
                            PermissionId = new Guid("30000001-0000-0000-0000-000000000001"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("5000000a-0000-0000-0000-00000000000a"),
                            PermissionId = new Guid("30000002-0000-0000-0000-000000000002"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("5000000b-0000-0000-0000-00000000000b"),
                            PermissionId = new Guid("30000003-0000-0000-0000-000000000003"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("5000000c-0000-0000-0000-00000000000c"),
                            PermissionId = new Guid("30000004-0000-0000-0000-000000000004"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("5000000d-0000-0000-0000-00000000000d"),
                            PermissionId = new Guid("10000001-0000-0000-0000-000000000001"),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("5000000e-0000-0000-0000-00000000000e"),
                            PermissionId = new Guid("30000001-0000-0000-0000-000000000001"),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000001"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000003"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000004"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000005"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000006"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000007"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000008"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000009"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            PermissionId = new Guid("10000000-0000-0000-0000-00000000000a"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            PermissionId = new Guid("10000000-0000-0000-0000-00000000000b"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            PermissionId = new Guid("10000000-0000-0000-0000-00000000000c"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000013"),
                            PermissionId = new Guid("10000000-0000-0000-0000-00000000000d"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000014"),
                            PermissionId = new Guid("10000000-0000-0000-0000-00000000000e"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000015"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000001"),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000016"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000017"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000006"),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000018"),
                            PermissionId = new Guid("10000000-0000-0000-0000-00000000000b"),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("ObserverNetLite.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8e445865-a24d-4543-a6c6-9443d048cdb9"),
                            Email = "admin@observernetlite.com",
                            Password = "0192023a7bbd73250516f069df18b500",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("9e225865-a24d-4543-a6c6-9443d048cdb9"),
                            Email = "guest@observernetlite.com",
                            Password = "fcf41657f02f88137a1bcf068a32c0a3",
                            UserName = "guest"
                        });
                });

            modelBuilder.Entity("ObserverNetLite.Core.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("70000001-0000-0000-0000-000000000001"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("8e445865-a24d-4543-a6c6-9443d048cdb9")
                        },
                        new
                        {
                            Id = new Guid("70000002-0000-0000-0000-000000000002"),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UserId = new Guid("9e225865-a24d-4543-a6c6-9443d048cdb9")
                        });
                });

            modelBuilder.Entity("ObserverNetLite.Core.Entities.Menu", b =>
                {
                    b.HasOne("ObserverNetLite.Core.Entities.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ObserverNetLite.Core.Entities.MenuPermission", b =>
                {
                    b.HasOne("ObserverNetLite.Core.Entities.Menu", "Menu")
                        .WithMany("MenuPermissions")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObserverNetLite.Core.Entities.Permission", "Permission")
                        .WithMany("MenuPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("ObserverNetLite.Core.Entities.RolePermission", b =>
                {
                    b.HasOne("ObserverNetLite.Core.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObserverNetLite.Core.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ObserverNetLite.Core.Entities.UserRole", b =>
                {
                    b.HasOne("ObserverNetLite.Core.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObserverNetLite.Core.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ObserverNetLite.Core.Entities.Menu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MenuPermissions");
                });

            modelBuilder.Entity("ObserverNetLite.Core.Entities.Permission", b =>
                {
                    b.Navigation("MenuPermissions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ObserverNetLite.Core.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ObserverNetLite.Core.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
