services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # Optional version of Node.js
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace:cached
    ports:
      - "5401:80"
    networks:
      - app-network
    depends_on:
      - db
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ObserverNetLiteDevDb
    ports:
      - "5402:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  app-network:

volumes:
  postgres-data: